# Generated by Django 4.0.2 on 2022-03-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/user-profile.png', null=True, upload_to='profile_pics'),
        ),
    ]
