# Generated by Django 4.0.2 on 2022-03-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_filemessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='FileMessages',
        ),
    ]
