# Generated by Django 3.1.8 on 2021-05-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210503_1327'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='users.Comments'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_list',
        ),
        migrations.AddField(
            model_name='user',
            name='created_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='created', to='auctions.ActiveListings'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='won_list',
        ),
        migrations.AddField(
            model_name='user',
            name='won_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='won', to='auctions.ActiveListings'),
        ),
    ]
