# Generated by Django 3.1.8 on 2021-05-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210503_1327'),
        ('users', '0002_auto_20210503_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watched_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='watched', to='auctions.ActiveListings'),
        ),
    ]
