# Generated by Django 3.1.8 on 2021-05-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210503_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activelistings',
            old_name='listings',
            new_name='category',
        ),
    ]
