# Generated by Django 3.1.8 on 2021-05-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210503_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activelistings',
            old_name='created_list',
            new_name='user',
        ),
    ]
