# Generated by Django 3.1.8 on 2021-05-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210505_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
