# Generated by Django 3.2.9 on 2022-01-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='nbids',
            field=models.IntegerField(default=0),
        ),
    ]
