# Generated by Django 4.0.2 on 2022-03-23 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, max_length=1024, null=True, unique=True)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pizza', 'pizza'), ('pasta', 'pasta'), ('burger', 'burger'), ('drinks', 'drinks'), ('salads', 'salads'), ('dessert', 'dessert')], max_length=10)),
                ('quantity', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('new', 'new'), ('sale', 'sale'), ('defualt', 'defualt'), ('out of stock', 'out of stock')], default='defualt', max_length=25)),
                ('ordercount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='#123456', max_length=7, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='#18776527', max_length=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('Mastercard', 'Mastercard'), ('Visa', 'Visa'), ('Bank Account', 'Bank Account'), ('Paypal', 'Paypal')], default='Mastercard', max_length=15)),
                ('paid', models.BooleanField(choices=[(0, 'upon receipt'), (1, 'paid')], default=0)),
                ('status', models.BooleanField(choices=[(0, 'Delevering'), (1, 'Delivered')], default=0)),
                ('orders', models.ManyToManyField(related_name='orders', to='orders.Order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
