# Generated by Django 4.0.2 on 2022-03-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.CharField(choices=[('upon receipt', 'upon receipt'), ('paid', 'paid')], default='upon receipt', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Delevering', 'Delevering'), ('Delivered', 'Delivered')], default='Delevering', max_length=15),
        ),
    ]
