# Generated by Django 4.0.2 on 2022-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name': 'table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AlterField(
            model_name='tables',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
